Dynamic\Locations\Model\Location:
  extensions:
    - Dynamic\Elements\Locations\Extension\LocationDataExtension

Dynamic\Locations\Model\LocationCategory:
  extensions:
    - Dynamic\Elements\Locations\Extension\LocationCategoryDataExtension